application.secret="i<UxBonrf0nfF6[qauf3VO`6Z/uX@86<Eup_IQd?7t7@qklE0Lul85OC:fPwHL^^"
application.langs="en"

mongodb.servers = ["localhost:27017"]
mongodb.db = "peloti"

mail.failTo=""
mail.host=""
mail.port=465
mail.username=""
mail.password=""

logger.root=ERROR
logger.play=INFO
logger.application=DEBUG

application.global=global.Global

# Information needed by the exception processor
jira.exceptionProcessor.enabled=true
jira.exceptionProcessor.projectKey=PA
jira.exceptionProcessor.componentName=PeLoTi
# Hash is the default
#jira.exceptionProcessor.hashCustomFieldName=Hash
# 1 is the default (Bug)
#jira.exceptionProcessor.issueType=1

# Used when the connection to Jira failed, note that the error is also logged
jira.exceptionProcessor.mail.from.name=PeLoTi
jira.exceptionProcessor.mail.from.address="noreply@rhinofly.net"
jira.exceptionProcessor.mail.to.name=Play
jira.exceptionProcessor.mail.to.address="play+error@rhinofly.nl"